### ISSUE TITLE
SMF Run error

### ISSUE THREAD

**Issue by Amber321321** [s5uishida/free5gc_ueransim_ulcl_sample_config#1]
Hi Shigeru,

I have been working on the ULCL test environment, but I stuck with the run free5gc with SMF run error notice. The error notice is below: " Yaml: line 23: did not find the expected key and SMF Run error: Failed to initialize !! " 

I have been checking many times regarding the compiling issue but still could not solve it. 

I wonder if you could help this out. Many thanks!

Kind regards,
Amber

**Comment by s5uishida** [comment]
Hi @Amber321321 

No YAML error occurred in my environment.
I think you probably have a syntax error somewhere in your YAML.

**Comment by Amber321321** [comment]
Hi Shigeru,

Thank you for your quick reply.

I have created a new SMF config file. The environment was working now. All good.  Many thanks. 

One more question, in terms of the docker network, I just simply created a new VM with docker and verified the connectivity with 5G.

I wonder if my understanding is right or wrong. 

Kind regards,
Amber

**Comment by s5uishida** [comment]
Hi @Amber321321 

It's enough to confirm that packets going to the network set in `uerouting.yaml` are routed as expected in I-UPF.
I used a Docker network as a simple example for this.

I think you may check ULCL with any easy configuration for you.

**Comment by Amber321321** [comment]
Hi Shigeru,

Thank you for your reply. Got it. Many thanks!

Kind regards
Amber
